mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #mybatis日志打印
    map-underscore-to-camel-case: true #驼峰映射

mchSerialNo: 6C73136A86F7E686E6526C0E698014C6245D01D0 #微信商户证书序列号
apiV3Key: e10adc3949ba59abbe56e057f20f883e # 微信apiv3秘钥
#微信商户私钥
privateKey: |
  -----BEGIN PRIVATE KEY-----
  MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC9flEvcFvmimai
  oCUA54iR+DhHaiqovOFuAX9gTP6MDYqyog3RBfrcZF4IKpCKWTLj4ZH1lM/ZceJM
  uAx7VrSrJD1HuDC/zj4NgVmhU5fKi25BBrtRMcTJEz0+7RA/XxpRXiKfT6WqTfvv
  uMk0hEorFk/olcg6K6gC7uO34o537qZBEG4dfP6EXZyPC336c3090Guz9r/5+k2+
  nxi+7r4T1kdALAEp2ncMuLrL0pJwOX8YwSsHWxNQFHzwT3pNFbsm7ZIHeSrHzG/N
  eh+OOCdMU2KAPWWkl0z47P4v9z2n1faiujAvnf7Dh4r/B9AjZyHxRwozgmr6HzaU
  /MA+yc6zAgMBAAECggEBAI7Qkf1v8EN7kckFa34YAk0JR9lDAa201S3kgQyiWsJR
  PnRNQJ6FpEDQgDIlalRqz7kB+9Cb/F7EvyrVF8spWPcXU/wmrM8ScKAbGeNFrkQf
  +9OUcD7MhKSLFIDFiJZKZfpnOS7ah2AocDWHDlW/UmrQ4R7JLGPzHShAxW2EmZ12
  +uVhBXPi0YRr1q2ISXfmJABQ+FNGc+AG0L+3HJfzzDeeeiXA/VR4C5cqRfr/OrpN
  +1TE20+9GJ5wj3jOPiwPUxOZ1t/kxRGlrPdaaklIngKdv5k/uH/Cu9b6JGfP4YJu
  SF3pifHJEBA69zVfedvoXHRlGxxyevTI1/CQf1Y9whkCgYEA3HZhAcaLdVbvoBqZ
  uec5HPAg6EhZp78/eGVLyK6F4Jd6XG+5kxNIQX8Tr0s9D+1A+PEVgewaqCA9FLg/
  WUeZGc8JdPqVT2O4S+1r64UrIGEVbNWBBLBDaXC9A02NbFhcW0ciF25loy27v5FO
  qOGxZFWt5UYH8CExHcSgrpPIkncCgYEA3An4GVc/dX8lmyy5K8d5+0PmgDX7YFo6
  YDj4HMtYXffdTLk+CmcV+r3aDMaf+xGZ4XAXLLaY4lWSeYcuiDjgy28oWsJ0bfjd
  uLKMJm0zck15pSEp97vClR7+tY2ABQN+lrUryOZbEY0AIScBAhaE/lAJ6AvTmR1A
  mvMigLlJ2KUCgYBQsNdSogvbF8W+8N2BKHtD9zPkMM730cz2UQUK363KhUbY3F+s
  0CrrJgrbZwtjb/AO7ZZ0pikfjiUtFz7Ae68yvg91DF5n31TOHYkZe/VL9Zy05/Q/
  9g/GYOgddF4l4LV1BzUYJGT48707IYEL2QdndOCgASDYqB1lCtnQ6/BGgwKBgAEf
  E+KdLTeeFET8L11nwNlk+THCFKvjCdUftTQAXUztTHVtpEFNUTFb8laKVJpk9pHN
  jnCt5Y2RvhNcewI6t/qRcHU19H3y/L5KOqifedmlR29uAda/YDh+VfH67KIZ6HVA
  Kx70/ZXTUCLbHggysS7SnZpPJR7spT2k65IYX6X5AoGARlK5fWpgW5W2D9iwX5Xr
  F0d9i/X/GH7Jl46IfnF2AfQq+FG/yaBqQSX1SxD0bZ9mtzX1DvIEVJaEhLrInDpy
  C2wF9h4CTUM5IywvFwg0oAVExS8rfaC+1ITykUqp0kwST/b7feoUO56cHH6oQYBP
  V505tAN1y46r6LbIGvsPrHo=
  -----END PRIVATE KEY-----
appId: wx96600d2c9189b7bb #微信appId
mchId: 1611845480 #微信商户号
appSecret: f4cf4ea6c6020bd2a3ab57324b04f643 #秘钥













